// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDil7cgqG-BXSur5yulAJ6qfebeeYn9OWY',
    appId: '1:706567728840:web:1b963769483f3e962dfffd',
    messagingSenderId: '706567728840',
    projectId: 'eventcible',
    authDomain: 'eventcible.firebaseapp.com',
    databaseURL: 'https://eventcible-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eventcible.appspot.com',
    measurementId: 'G-ECNPBTT1RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdAbxPUcp_xIRKzmkw_rHHUwTJJRzseDs',
    appId: '1:706567728840:android:cee192c9648192372dfffd',
    messagingSenderId: '706567728840',
    projectId: 'eventcible',
    databaseURL: 'https://eventcible-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eventcible.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUFO6UrAUUPK_FxL6xw6zhf9Ahdmff9g',
    appId: '1:706567728840:ios:76df55b34ab4c45c2dfffd',
    messagingSenderId: '706567728840',
    projectId: 'eventcible',
    databaseURL: 'https://eventcible-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eventcible.appspot.com',
    iosBundleId: 'com.example.mobileSecurityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpUFO6UrAUUPK_FxL6xw6zhf9Ahdmff9g',
    appId: '1:706567728840:ios:76df55b34ab4c45c2dfffd',
    messagingSenderId: '706567728840',
    projectId: 'eventcible',
    databaseURL: 'https://eventcible-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eventcible.appspot.com',
    iosBundleId: 'com.example.mobileSecurityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDil7cgqG-BXSur5yulAJ6qfebeeYn9OWY',
    appId: '1:706567728840:web:1b963769483f3e962dfffd',
    messagingSenderId: '706567728840',
    projectId: 'eventcible',
    authDomain: 'eventcible.firebaseapp.com',
    databaseURL: 'https://eventcible-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eventcible.appspot.com',
    measurementId: 'G-ECNPBTT1RB',
  );
}
